# A string used to distinguish different Supabase projects on the same host. Defaults to the
# working directory name when running `supabase init`.
project_id = "workla"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[auth]
enabled = true
port = 54324

[auth.external.phone]
enabled = true

[auth.sms.test_otp]
# Example Test Number for local development
"+919999999999" = "123456"
# You can add your own number here like:
# "+918888888888" = "654321"

[storage]
enabled = true
port = 54326
